import { db } from '@/db';
import { pricingFactors } from '@/db/schema';

async function main() {
    const samplePricingFactors = [
        // iPhone 15 Pro - Apple premium brand, high demand
        {
            productId: 1,
            brandValue: 9.5,
            marketDemand: 9.2,
            conditionScore: 9.8,
            usageDuration: 2,
            functionalityScore: 9.9,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        // MacBook Air M3 - Apple premium, high demand
        {
            productId: 2,
            brandValue: 9.2,
            marketDemand: 8.8,
            conditionScore: 9.5,
            usageDuration: 3,
            functionalityScore: 9.7,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        // AirPods Pro - Apple premium, high demand
        {
            productId: 3,
            brandValue: 9.0,
            marketDemand: 8.5,
            conditionScore: 8.2,
            usageDuration: 8,
            functionalityScore: 8.8,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        // Samsung Galaxy S24 - Premium Android, good demand
        {
            productId: 4,
            brandValue: 7.8,
            marketDemand: 7.5,
            conditionScore: 9.0,
            usageDuration: 4,
            functionalityScore: 9.3,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        // Dell XPS 13 - Mid-range brand, moderate demand
        {
            productId: 5,
            brandValue: 6.5,
            marketDemand: 6.8,
            conditionScore: 8.5,
            usageDuration: 6,
            functionalityScore: 8.9,
            createdAt: new Date('2024-01-30').toISOString(),
            updatedAt: new Date('2024-01-30').toISOString(),
        },
        // Sony WH-1000XM4 - Premium audio brand
        {
            productId: 6,
            brandValue: 8.2,
            marketDemand: 7.8,
            conditionScore: 7.5,
            usageDuration: 12,
            functionalityScore: 8.5,
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        // Nintendo Switch - Gaming console, high demand
        {
            productId: 7,
            brandValue: 8.0,
            marketDemand: 8.5,
            conditionScore: 7.8,
            usageDuration: 10,
            functionalityScore: 9.1,
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
        // iPad Pro 2023 - Apple premium tablet
        {
            productId: 8,
            brandValue: 9.3,
            marketDemand: 8.2,
            conditionScore: 9.2,
            usageDuration: 5,
            functionalityScore: 9.6,
            createdAt: new Date('2024-02-08').toISOString(),
            updatedAt: new Date('2024-02-08').toISOString(),
        },
        // Google Pixel 8 - Google brand, moderate demand
        {
            productId: 9,
            brandValue: 7.2,
            marketDemand: 6.5,
            conditionScore: 8.8,
            usageDuration: 6,
            functionalityScore: 9.0,
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        // HP Pavilion - Budget laptop brand
        {
            productId: 10,
            brandValue: 4.5,
            marketDemand: 5.2,
            conditionScore: 6.8,
            usageDuration: 18,
            functionalityScore: 7.5,
            createdAt: new Date('2024-02-12').toISOString(),
            updatedAt: new Date('2024-02-12').toISOString(),
        },
        // Canon EOS R5 - Premium camera brand
        {
            productId: 11,
            brandValue: 8.5,
            marketDemand: 7.0,
            conditionScore: 8.0,
            usageDuration: 14,
            functionalityScore: 8.8,
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        // Xiaomi Mi 13 - Budget flagship, good value
        {
            productId: 12,
            brandValue: 5.8,
            marketDemand: 6.8,
            conditionScore: 7.2,
            usageDuration: 16,
            functionalityScore: 8.2,
            createdAt: new Date('2024-02-18').toISOString(),
            updatedAt: new Date('2024-02-18').toISOString(),
        },
        // Microsoft Surface Pro 9 - Premium Windows tablet
        {
            productId: 13,
            brandValue: 7.5,
            marketDemand: 6.8,
            conditionScore: 8.3,
            usageDuration: 8,
            functionalityScore: 8.7,
            createdAt: new Date('2024-02-20').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
        },
        // LG OLED TV 55" - Premium TV brand
        {
            productId: 14,
            brandValue: 7.8,
            marketDemand: 7.2,
            conditionScore: 9.0,
            usageDuration: 6,
            functionalityScore: 9.4,
            createdAt: new Date('2024-02-22').toISOString(),
            updatedAt: new Date('2024-02-22').toISOString(),
        },
        // OnePlus 11 - Mid-range flagship killer
        {
            productId: 15,
            brandValue: 6.5,
            marketDemand: 6.2,
            conditionScore: 7.8,
            usageDuration: 12,
            functionalityScore: 8.5,
            createdAt: new Date('2024-02-25').toISOString(),
            updatedAt: new Date('2024-02-25').toISOString(),
        },
        // Lenovo ThinkPad X1 - Business laptop, good brand
        {
            productId: 16,
            brandValue: 7.2,
            marketDemand: 6.5,
            conditionScore: 6.5,
            usageDuration: 20,
            functionalityScore: 7.8,
            createdAt: new Date('2024-02-28').toISOString(),
            updatedAt: new Date('2024-02-28').toISOString(),
        },
        // Apple Watch Series 9 - Apple premium wearable
        {
            productId: 17,
            brandValue: 9.0,
            marketDemand: 8.3,
            conditionScore: 8.5,
            usageDuration: 7,
            functionalityScore: 9.2,
            createdAt: new Date('2024-03-01').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
        },
        // Bose QuietComfort 45 - Premium audio brand
        {
            productId: 18,
            brandValue: 8.0,
            marketDemand: 7.5,
            conditionScore: 7.0,
            usageDuration: 15,
            functionalityScore: 8.3,
            createdAt: new Date('2024-03-03').toISOString(),
            updatedAt: new Date('2024-03-03').toISOString(),
        },
        // Asus ROG Gaming Laptop - Gaming brand
        {
            productId: 19,
            brandValue: 6.8,
            marketDemand: 7.2,
            conditionScore: 7.5,
            usageDuration: 11,
            functionalityScore: 8.8,
            createdAt: new Date('2024-03-05').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
        },
        // Huawei MateBook - Mid-range laptop
        {
            productId: 20,
            brandValue: 5.5,
            marketDemand: 4.8,
            conditionScore: 6.8,
            usageDuration: 22,
            functionalityScore: 7.2,
            createdAt: new Date('2024-03-08').toISOString(),
            updatedAt: new Date('2024-03-08').toISOString(),
        },
        // PlayStation 5 - Premium gaming console
        {
            productId: 21,
            brandValue: 8.8,
            marketDemand: 9.0,
            conditionScore: 8.8,
            usageDuration: 9,
            functionalityScore: 9.5,
            createdAt: new Date('2024-03-10').toISOString(),
            updatedAt: new Date('2024-03-10').toISOString(),
        },
        // Samsung Galaxy Buds Pro - Mid-premium earbuds
        {
            productId: 22,
            brandValue: 7.0,
            marketDemand: 6.8,
            conditionScore: 6.5,
            usageDuration: 18,
            functionalityScore: 7.5,
            createdAt: new Date('2024-03-12').toISOString(),
            updatedAt: new Date('2024-03-12').toISOString(),
        },
        // iPhone 13 - Apple, slightly older model
        {
            productId: 23,
            brandValue: 9.2,
            marketDemand: 8.0,
            conditionScore: 7.8,
            usageDuration: 15,
            functionalityScore: 8.9,
            createdAt: new Date('2024-03-15').toISOString(),
            updatedAt: new Date('2024-03-15').toISOString(),
        },
        // Acer Predator Gaming Monitor - Gaming peripherals
        {
            productId: 24,
            brandValue: 6.2,
            marketDemand: 6.5,
            conditionScore: 8.2,
            usageDuration: 10,
            functionalityScore: 8.6,
            createdAt: new Date('2024-03-18').toISOString(),
            updatedAt: new Date('2024-03-18').toISOString(),
        },
        // Dyson V15 Vacuum - Premium appliance brand
        {
            productId: 25,
            brandValue: 8.5,
            marketDemand: 7.8,
            conditionScore: 7.2,
            usageDuration: 13,
            functionalityScore: 8.8,
            createdAt: new Date('2024-03-20').toISOString(),
            updatedAt: new Date('2024-03-20').toISOString(),
        },
        // Realme GT Neo - Budget flagship
        {
            productId: 26,
            brandValue: 4.8,
            marketDemand: 5.5,
            conditionScore: 6.2,
            usageDuration: 24,
            functionalityScore: 7.0,
            createdAt: new Date('2024-03-22').toISOString(),
            updatedAt: new Date('2024-03-22').toISOString(),
        },
        // MacBook Pro 16" M2 - Apple premium laptop
        {
            productId: 27,
            brandValue: 9.5,
            marketDemand: 8.5,
            conditionScore: 9.3,
            usageDuration: 4,
            functionalityScore: 9.8,
            createdAt: new Date('2024-03-25').toISOString(),
            updatedAt: new Date('2024-03-25').toISOString(),
        },
        // JBL Charge 5 Speaker - Mid-range audio
        {
            productId: 28,
            brandValue: 6.0,
            marketDemand: 6.5,
            conditionScore: 7.0,
            usageDuration: 14,
            functionalityScore: 7.8,
            createdAt: new Date('2024-03-28').toISOString(),
            updatedAt: new Date('2024-03-28').toISOString(),
        },
        // Tesla Model 3 Screen Unit - Niche automotive tech
        {
            productId: 29,
            brandValue: 8.5,
            marketDemand: 4.2,
            conditionScore: 5.8,
            usageDuration: 30,
            functionalityScore: 6.5,
            createdAt: new Date('2024-03-30').toISOString(),
            updatedAt: new Date('2024-03-30').toISOString(),
        },
        // Oppo Find X5 Pro - Mid-premium phone
        {
            productId: 30,
            brandValue: 6.2,
            marketDemand: 5.8,
            conditionScore: 7.5,
            usageDuration: 16,
            functionalityScore: 8.1,
            createdAt: new Date('2024-04-01').toISOString(),
            updatedAt: new Date('2024-04-01').toISOString(),
        },
        // Razer DeathAdder Gaming Mouse - Gaming peripherals
        {
            productId: 31,
            brandValue: 7.0,
            marketDemand: 6.8,
            conditionScore: 6.8,
            usageDuration: 20,
            functionalityScore: 8.2,
            createdAt: new Date('2024-04-03').toISOString(),
            updatedAt: new Date('2024-04-03').toISOString(),
        },
        // Kindle Paperwhite - Amazon e-reader
        {
            productId: 32,
            brandValue: 7.5,
            marketDemand: 6.0,
            conditionScore: 8.0,
            usageDuration: 12,
            functionalityScore: 8.5,
            createdAt: new Date('2024-04-05').toISOString(),
            updatedAt: new Date('2024-04-05').toISOString(),
        },
        // Vivo X90 Pro - Mid-range flagship
        {
            productId: 33,
            brandValue: 5.8,
            marketDemand: 5.2,
            conditionScore: 7.8,
            usageDuration: 11,
            functionalityScore: 8.3,
            createdAt: new Date('2024-04-08').toISOString(),
            updatedAt: new Date('2024-04-08').toISOString(),
        },
        // GoPro Hero 11 - Action camera
        {
            productId: 34,
            brandValue: 7.8,
            marketDemand: 6.5,
            conditionScore: 6.5,
            usageDuration: 18,
            functionalityScore: 7.8,
            createdAt: new Date('2024-04-10').toISOString(),
            updatedAt: new Date('2024-04-10').toISOString(),
        },
        // Microsoft Xbox Series X - Gaming console
        {
            productId: 35,
            brandValue: 8.2,
            marketDemand: 8.0,
            conditionScore: 8.5,
            usageDuration: 8,
            functionalityScore: 9.2,
            createdAt: new Date('2024-04-12').toISOString(),
            updatedAt: new Date('2024-04-12').toISOString(),
        },
        // Logitech MX Master 3 Mouse - Premium peripherals
        {
            productId: 36,
            brandValue: 7.2,
            marketDemand: 7.0,
            conditionScore: 7.2,
            usageDuration: 15,
            functionalityScore: 8.5,
            createdAt: new Date('2024-04-15').toISOString(),
            updatedAt: new Date('2024-04-15').toISOString(),
        },
        // Honor Magic 5 Pro - Mid-range brand
        {
            productId: 37,
            brandValue: 5.5,
            marketDemand: 5.0,
            conditionScore: 6.8,
            usageDuration: 19,
            functionalityScore: 7.5,
            createdAt: new Date('2024-04-18').toISOString(),
            updatedAt: new Date('2024-04-18').toISOString(),
        },
        // DJI Mini 3 Drone - Niche tech product
        {
            productId: 38,
            brandValue: 8.0,
            marketDemand: 5.5,
            conditionScore: 7.5,
            usageDuration: 14,
            functionalityScore: 8.0,
            createdAt: new Date('2024-04-20').toISOString(),
            updatedAt: new Date('2024-04-20').toISOString(),
        },
        // Fitbit Versa 4 - Fitness tracker
        {
            productId: 39,
            brandValue: 6.5,
            marketDemand: 6.0,
            conditionScore: 6.0,
            usageDuration: 22,
            functionalityScore: 7.2,
            createdAt: new Date('2024-04-22').toISOString(),
            updatedAt: new Date('2024-04-22').toISOString(),
        },
        // Steam Deck - Gaming handheld
        {
            productId: 40,
            brandValue: 8.0,
            marketDemand: 7.8,
            conditionScore: 7.0,
            usageDuration: 16,
            functionalityScore: 8.5,
            createdAt: new Date('2024-04-25').toISOString(),
            updatedAt: new Date('2024-04-25').toISOString(),
        },
        // Nothing Phone 2 - Niche brand
        {
            productId: 41,
            brandValue: 5.0,
            marketDemand: 4.5,
            conditionScore: 8.2,
            usageDuration: 9,
            functionalityScore: 8.0,
            createdAt: new Date('2024-04-28').toISOString(),
            updatedAt: new Date('2024-04-28').toISOString(),
        },
        // Panasonic Lumix GH6 - Professional camera
        {
            productId: 42,
            brandValue: 7.5,
            marketDemand: 5.8,
            conditionScore: 6.8,
            usageDuration: 20,
            functionalityScore: 8.2,
            createdAt: new Date('2024-04-30').toISOString(),
            updatedAt: new Date('2024-04-30').toISOString(),
        },
        // Samsung Galaxy Tab S9 - Premium Android tablet
        {
            productId: 43,
            brandValue: 7.5,
            marketDemand: 6.8,
            conditionScore: 8.8,
            usageDuration: 6,
            functionalityScore: 9.0,
            createdAt: new Date('2024-05-02').toISOString(),
            updatedAt: new Date('2024-05-02').toISOString(),
        },
        // Corsair K95 Gaming Keyboard - Gaming peripherals
        {
            productId: 44,
            brandValue: 7.0,
            marketDemand: 6.2,
            conditionScore: 6.5,
            usageDuration: 24,
            functionalityScore: 7.8,
            createdAt: new Date('2024-05-05').toISOString(),
            updatedAt: new Date('2024-05-05').toISOString(),
        },
        // Motorola Edge 40 Pro - Mid-range phone
        {
            productId: 45,
            brandValue: 5.2,
            marketDemand: 4.8,
            conditionScore: 7.2,
            usageDuration: 17,
            functionalityScore: 7.8,
            createdAt: new Date('2024-05-08').toISOString(),
            updatedAt: new Date('2024-05-08').toISOString(),
        },
        // Nikon Z9 - Professional camera
        {
            productId: 46,
            brandValue: 8.2,
            marketDemand: 6.0,
            conditionScore: 8.5,
            usageDuration: 10,
            functionalityScore: 9.0,
            createdAt: new Date('2024-05-10').toISOString(),
            updatedAt: new Date('2024-05-10').toISOString(),
        },
        // Anker PowerCore Power Bank - Accessories
        {
            productId: 47,
            brandValue: 6.0,
            marketDemand: 6.5,
            conditionScore: 5.8,
            usageDuration: 28,
            functionalityScore: 6.8,
            createdAt: new Date('2024-05-12').toISOString(),
            updatedAt: new Date('2024-05-12').toISOString(),
        },
        // Framework Laptop - Niche modular laptop
        {
            productId: 48,
            brandValue: 6.8,
            marketDemand: 4.0,
            conditionScore: 7.8,
            usageDuration: 12,
            functionalityScore: 8.5,
            createdAt: new Date('2024-05-15').toISOString(),
            updatedAt: new Date('2024-05-15').toISOString(),
        },
        // TCL 65" QLED TV - Budget premium TV
        {
            productId: 49,
            brandValue: 5.5,
            marketDemand: 6.2,
            conditionScore: 8.5,
            usageDuration: 8,
            functionalityScore: 8.2,
            createdAt: new Date('2024-05-18').toISOString(),
            updatedAt: new Date('2024-05-18').toISOString(),
        },
        // Meta Quest 3 VR Headset - VR gaming
        {
            productId: 50,
            brandValue: 7.8,
            marketDemand: 7.0,
            conditionScore: 8.0,
            usageDuration: 11,
            functionalityScore: 8.8,
            createdAt: new Date('2024-05-20').toISOString(),
            updatedAt: new Date('2024-05-20').toISOString(),
        },
        // Garmin Fenix 7 - Premium fitness watch
        {
            productId: 51,
            brandValue: 8.0,
            marketDemand: 6.5,
            conditionScore: 7.0,
            usageDuration: 18,
            functionalityScore: 8.3,
            createdAt: new Date('2024-05-22').toISOString(),
            updatedAt: new Date('2024-05-22').toISOString(),
        },
        // RedMi Note 12 Pro - Budget phone
        {
            productId: 52,
            brandValue: 4.5,
            marketDemand: 6.0,
            conditionScore: 6.5,
            usageDuration: 21,
            functionalityScore: 7.5,
            createdAt: new Date('2024-05-25').toISOString(),
            updatedAt: new Date('2024-05-25').toISOString(),
        },
        // ASUS ROG Ally - Gaming handheld
        {
            productId: 53,
            brandValue: 7.2,
            marketDemand: 6.5,
            conditionScore: 7.5,
            usageDuration: 13,
            functionalityScore: 8.0,
            createdAt: new Date('2024-05-28').toISOString(),
            updatedAt: new Date('2024-05-28').toISOString(),
        },
        // Sonos One Speaker - Premium audio
        {
            productId: 54,
            brandValue: 7.8,
            marketDemand: 6.8,
            conditionScore: 6.8,
            usageDuration: 19,
            functionalityScore: 8.0,
            createdAt: new Date('2024-05-30').toISOString(),
            updatedAt: new Date('2024-05-30').toISOString(),
        },
        // Surface Laptop Studio - Premium Windows laptop
        {
            productId: 55,
            brandValue: 7.5,
            marketDemand: 5.8,
            conditionScore: 8.2,
            usageDuration: 9,
            functionalityScore: 8.7,
            createdAt: new Date('2024-06-01').toISOString(),
            updatedAt: new Date('2024-06-01').toISOString(),
        },
        // iPhone 12 Pro - Older Apple flagship
        {
            productId: 56,
            brandValue: 9.0,
            marketDemand: 7.2,
            conditionScore: 6.8,
            usageDuration: 24,
            functionalityScore: 8.0,
            createdAt: new Date('2024-06-03').toISOString(),
            updatedAt: new Date('2024-06-03').toISOString(),
        },
        // Google Nest Hub Max - Smart home
        {
            productId: 57,
            brandValue: 6.8,
            marketDemand: 5.5,
            conditionScore: 7.2,
            usageDuration: 16,
            functionalityScore: 7.8,
            createdAt: new Date('2024-06-05').toISOString(),
            updatedAt: new Date('2024-06-05').toISOString(),
        },
        // Blackmagic Pocket Cinema Camera - Professional video
        {
            productId: 58,
            brandValue: 7.5,
            marketDemand: 4.8,
            conditionScore: 7.0,
            usageDuration: 22,
            functionalityScore: 7.5,
            createdAt: new Date('2024-06-08').toISOString(),
            updatedAt: new Date('2024-06-08').toISOString(),
        },
        // Alienware Aurora Gaming Desktop - Premium gaming
        {
            productId: 59,
            brandValue: 8.0,
            marketDemand: 7.0,
            conditionScore: 8.0,
            usageDuration: 12,
            functionalityScore: 9.0,
            createdAt: new Date('2024-06-10').toISOString(),
            updatedAt: new Date('2024-06-10').toISOString(),
        },
        // Beats Studio Pro - Mid-premium audio
        {
            productId: 60,
            brandValue: 7.0,
            marketDemand: 6.8,
            conditionScore: 6.2,
            usageDuration: 20,
            functionalityScore: 7.5,
            createdAt: new Date('2024-06-12').toISOString(),
            updatedAt: new Date('2024-06-12').toISOString(),
        },
        // ROG Phone 7 - Gaming phone niche
        {
            productId: 61,
            brandValue: 6.5,
            marketDemand: 5.0,
            conditionScore: 7.8,
            usageDuration: 14,
            functionalityScore: 8.5,
            createdAt: new Date('2024-06-15').toISOString(),
            updatedAt: new Date('2024-06-15').toISOString(),
        },
        // Epson EcoTank Printer - Office equipment
        {
            productId: 62,
            brandValue: 6.2,
            marketDemand: 5.8,
            conditionScore: 5.5,
            usageDuration: 30,
            functionalityScore: 6.5,
            createdAt: new Date('2024-06-18').toISOString(),
            updatedAt: new Date('2024-06-18').toISOString(),
        },
        // Rode PodMic - Professional audio equipment
        {
            productId: 63,
            brandValue: 7.5,
            marketDemand: 5.2,
            conditionScore: 8.5,
            usageDuration: 8,
            functionalityScore: 9.0,
            createdAt: new Date('2024-06-20').toISOString(),
            updatedAt: new Date('2024-06-20').toISOString(),
        },
        // Poco F5 Pro - Budget flagship
        {
            productId: 64,
            brandValue: 4.8,
            marketDemand: 6.2,
            conditionScore: 7.5,
            usageDuration: 15,
            functionalityScore: 8.0,
            createdAt: new Date('2024-06-22').toISOString(),
            updatedAt: new Date('2024-06-22').toISOString(),
        },
        // Elgato Stream Deck - Content creation
        {
            productId: 65,
            brandValue: 7.0,
            marketDemand: 5.8,
            conditionScore: 7.8,
            usageDuration: 12,
            functionalityScore: 8.5,
            createdAt: new Date('2024-06-25').toISOString(),
            updatedAt: new Date('2024-06-25').toISOString(),
        },
        // Magic Keyboard for iPad - Apple accessory
        {
            productId: 66,
            brandValue: 8.5,
            marketDemand: 6.5,
            conditionScore: 6.5,
            usageDuration: 20,
            functionalityScore: 8.0,
            createdAt: new Date('2024-06-28').toISOString(),
            updatedAt: new Date('2024-06-28').toISOString(),
        },
        // Gigabyte AORUS Gaming Monitor - Gaming display
        {
            productId: 67,
            brandValue: 6.8,
            marketDemand: 6.0,
            conditionScore: 7.2,
            usageDuration: 16,
            functionalityScore: 8.2,
            createdAt: new Date('2024-06-30').toISOString(),
            updatedAt: new Date('2024-06-30').toISOString(),
        },
        // Fairphone 5 - Sustainable phone niche
        {
            productId: 68,
            brandValue: 5.5,
            marketDemand: 3.8,
            conditionScore: 8.8,
            usageDuration: 6,
            functionalityScore: 7.8,
            createdAt: new Date('2024-07-02').toISOString(),
            updatedAt: new Date('2024-07-02').toISOString(),
        },
        // Audio-Technica ATH-M50x - Professional headphones
        {
            productId: 69,
            brandValue: 7.2,
            marketDemand: 6.8,
            conditionScore: 6.0,
            usageDuration: 25,
            functionalityScore: 7.5,
            createdAt: new Date('2024-07-05').toISOString(),
            updatedAt: new Date('2024-07-05').toISOString(),
        },
        // Intel NUC Mini PC - Niche computing
        {
            productId: 70,
            brandValue: 6.5,
            marketDemand: 4.5,
            conditionScore: 7.0,
            usageDuration: 18,
            functionalityScore: 7.8,
            createdAt: new Date('2024-07-08').toISOString(),
            updatedAt: new Date('2024-07-08').toISOString(),
        },
        // Oculus Rift S - Older VR headset
        {
            productId: 71,
            brandValue: 7.0,
            marketDemand: 4.2,
            conditionScore: 5.5,
            usageDuration: 32,
            functionalityScore: 6.0,
            createdAt: new Date('2024-07-10').toISOString(),
            updatedAt: new Date('2024-07-10').toISOString(),
        },
        // Sennheiser Momentum 4 - Premium audio
        {
            productId: 72,
            brandValue: 8.2,
            marketDemand: 6.2,
            conditionScore: 7.8,
            usageDuration: 13,
            functionalityScore: 8.7,
            createdAt: new Date('2024-07-12').toISOString(),
            updatedAt: new Date('2024-07-12').toISOString(),
        },
        // OnePlus Buds Pro 2 - Mid-range earbuds
        {
            productId: 73,
            brandValue: 5.8,
            marketDemand: 5.5,
            conditionScore: 6.8,
            usageDuration: 17,
            functionalityScore: 7.2,
            createdAt: new Date('2024-07-15').toISOString(),
            updatedAt: new Date('2024-07-15').toISOString(),
        },
        // MSI Creator Z16 Laptop - Content creation
        {
            productId: 74,
            brandValue: 6.8,
            marketDemand: 5.5,
            conditionScore: 7.5,
            usageDuration: 14,
            functionalityScore: 8.5,
            createdAt: new Date('2024-07-18').toISOString(),
            updatedAt: new Date('2024-07-18').toISOString(),
        },
        // Apple Mac Mini M2 - Compact desktop
        {
            productId: 75,
            brandValue: 9.0,
            marketDemand: 6.8,
            conditionScore: 8.8,
            usageDuration: 7,
            functionalityScore: 9.2,
            createdAt: new Date('2024-07-20').toISOString(),
            updatedAt: new Date('2024-07-20').toISOString(),
        },
        // Razer Blade 15 Gaming Laptop - Premium gaming
        {
            productId: 76,
            brandValue: 7.5,
            marketDemand: 7.0,
            conditionScore: 7.0,
            usageDuration: 17,
            functionalityScore: 8.2,
            createdAt: new Date('2024-07-22').toISOString(),
            updatedAt: new Date('2024-07-22').toISOString(),
        },
        // Xiaomi Mi Band 8 - Budget fitness tracker
        {
            productId: 77,
            brandValue: 4.5,
            marketDemand: 6.5,
            conditionScore: 5.8,
            usageDuration: 26,
            functionalityScore: 6.8,
            createdAt: new Date('2024-07-25').toISOString(),
            updatedAt: new Date('2024-07-25').toISOString(),
        },
        // Herman Miller Aeron Chair - Premium office furniture
        {
            productId: 78,
            brandValue: 8.8,
            marketDemand: 6.0,
            conditionScore: 6.8,
            usageDuration: 24,
            functionalityScore: 8.5,
            createdAt: new Date('2024-07-28').toISOString(),
            updatedAt: new Date('2024-07-28').toISOString(),
        },
        // Secretlab Titan Gaming Chair - Gaming furniture
        {
            productId: 79,
            brandValue: 7.2,
            marketDemand: 6.8,
            conditionScore: 7.2,
            usageDuration: 15,
            functionalityScore: 8.0,
            createdAt: new Date('2024-07-30').toISOString(),
            updatedAt: new Date('2024-07-30').toISOString(),
        },
        // Instant Pot Duo - Kitchen appliance
        {
            productId: 80,
            brandValue: 6.5,
            marketDemand: 6.2,
            conditionScore: 5.2,
            usageDuration: 28,
            functionalityScore: 6.8,
            createdAt: new Date('2024-08-01').toISOString(),
            updatedAt: new Date('2024-08-01').toISOString(),
        }
    ];

    await db.insert(pricingFactors).values(samplePricingFactors);
    
    console.log('✅ Pricing factors seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});