import { db } from '@/db';
import { productReviews } from '@/db/schema';

async function main() {
    const sampleReviews = [
        {
            productId: 1,
            userId: 2,
            rating: 5,
            content: '商品描述非常准确，iPhone 13的成色就像卖家说的九成新一样。卖家回复很及时，交易很顺利。物流也很快，第二天就收到了。性价比很高，推荐！',
            createdAt: new Date('2024-02-20').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
        },
        {
            productId: 2,
            userId: 3,
            rating: 4,
            content: 'MacBook works perfectly as described. Seller was responsive and honest about the minor scratches on the back. Fast shipping and good packaging. Only minor issue is the battery life is not as good as expected, but still acceptable for a used laptop.',
            createdAt: new Date('2024-02-22').toISOString(),
            updatedAt: new Date('2024-02-22').toISOString(),
        },
        {
            productId: 3,
            userId: 4,
            rating: 5,
            content: 'iPad Pro完全符合预期！屏幕没有划痕，功能都正常。卖家人很好，还送了原装充电器。比专卖店便宜很多，真的很值。强烈推荐这个卖家！',
            createdAt: new Date('2024-02-25').toISOString(),
            updatedAt: new Date('2024-02-25').toISOString(),
        },
        {
            productId: 4,
            userId: 5,
            rating: 3,
            content: 'AirPods sound quality is good but the case has more wear than shown in photos. Seller communication was okay but took a while to respond. Delivery was on time. Fair price for the condition but expected better based on description.',
            createdAt: new Date('2024-03-01').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
        },
        {
            productId: 5,
            userId: 6,
            rating: 4,
            content: 'Nintendo Switch运行流畅，Joy-Con没有漂移问题。卖家很诚实地告知了所有使用痕迹。包装很仔细，第三天收到货。价格合理，整体满意。',
            createdAt: new Date('2024-03-05').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
        },
        {
            productId: 1,
            userId: 7,
            rating: 5,
            content: 'Excellent transaction! iPhone condition exactly as described - like new. Seller responded within minutes to all questions. Super fast delivery, received in 1 day. Great value for money, would definitely buy from this seller again.',
            createdAt: new Date('2024-03-07').toISOString(),
            updatedAt: new Date('2024-03-07').toISOString(),
        },
        {
            productId: 6,
            userId: 8,
            rating: 4,
            content: 'PS5手柄状态不错，按键反应灵敏，摇杆也没有问题。卖家态度很好，回答问题很详细。快递包装也很安全。唯一小缺点是有轻微使用痕迹，但不影响使用。',
            createdAt: new Date('2024-03-10').toISOString(),
            updatedAt: new Date('2024-03-10').toISOString(),
        },
        {
            productId: 7,
            userId: 9,
            rating: 2,
            content: 'Apple Watch has some functionality issues that were not mentioned. Battery life is much shorter than expected. Seller was slow to respond and shipping took longer than promised. Price was fair but product condition not as good as described.',
            createdAt: new Date('2024-03-12').toISOString(),
            updatedAt: new Date('2024-03-12').toISOString(),
        },
        {
            productId: 8,
            userId: 10,
            rating: 5,
            content: 'Surface Pro平板电脑性能很好，触摸屏灵敏，续航也不错。卖家很专业，提供了详细的产品信息和使用建议。发货很快，包装专业。物超所值！',
            createdAt: new Date('2024-03-15').toISOString(),
            updatedAt: new Date('2024-03-15').toISOString(),
        },
        {
            productId: 9,
            userId: 2,
            rating: 4,
            content: 'Canon camera works great, all functions tested and working. Some minor cosmetic wear but nothing that affects performance. Seller was honest about condition and provided extra lens cap. Good communication and fast shipping.',
            createdAt: new Date('2024-03-18').toISOString(),
            updatedAt: new Date('2024-03-18').toISOString(),
        },
        {
            productId: 10,
            userId: 3,
            rating: 5,
            content: '戴森吸尘器吸力很强，各种刷头都有。卖家清洁得很干净，几乎像新的一样。客服态度很好，回复很及时。包装保护得很好，没有任何损坏。非常满意的购物体验！',
            createdAt: new Date('2024-03-20').toISOString(),
            updatedAt: new Date('2024-03-20').toISOString(),
        },
        {
            productId: 2,
            userId: 11,
            rating: 4,
            content: 'MacBook Pro performance is excellent for the price. Minor keyboard wear but all keys work perfectly. Seller provided original charger and was very helpful with setup questions. Fast delivery and secure packaging. Great deal overall.',
            createdAt: new Date('2024-03-22').toISOString(),
            updatedAt: new Date('2024-03-22').toISOString(),
        },
        {
            productId: 3,
            userId: 12,
            rating: 3,
            content: 'iPad功能正常，但是电池续航比描述的要差一些。屏幕有几个小划痕，虽然不太明显。卖家沟通还行，但回复不够及时。价格还算合理，但期望值更高一点。',
            createdAt: new Date('2024-03-25').toISOString(),
            updatedAt: new Date('2024-03-25').toISOString(),
        },
        {
            productId: 4,
            userId: 13,
            rating: 5,
            content: 'Perfect AirPods! Sound quality is amazing and battery life is still very good. Case looks almost new with minimal wear. Seller was super responsive and shipped same day. Excellent value for money, highly recommended!',
            createdAt: new Date('2024-03-28').toISOString(),
            updatedAt: new Date('2024-03-28').toISOString(),
        },
        {
            productId: 5,
            userId: 14,
            rating: 4,
            content: 'Switch主机和游戏都运行很好，屏幕清晰，控制器反应灵敏。有一些使用痕迹但不影响游戏体验。卖家很耐心回答问题，发货也很快。整体很满意！',
            createdAt: new Date('2024-03-30').toISOString(),
            updatedAt: new Date('2024-03-30').toISOString(),
        },
        {
            productId: 6,
            userId: 15,
            rating: 2,
            content: 'PS5 controller has stick drift issues that were not mentioned in the listing. Seller took a while to respond to messages. Shipping was delayed by 2 days. Price was okay but condition was worse than expected. Would not recommend.',
            createdAt: new Date('2024-04-02').toISOString(),
            updatedAt: new Date('2024-04-02').toISOString(),
        },
        {
            productId: 7,
            userId: 16,
            rating: 4,
            content: 'Apple Watch功能都正常，外观也还不错。表带有些磨损但可以接受。卖家态度很好，还教了我一些使用技巧。物流速度一般，但包装很仔细。性价比不错。',
            createdAt: new Date('2024-04-05').toISOString(),
            updatedAt: new Date('2024-04-05').toISOString(),
        },
        {
            productId: 8,
            userId: 17,
            rating: 5,
            content: 'Excellent Surface Pro tablet! Screen is pristine and performance is like new. Keyboard works perfectly and battery life is still great. Seller provided detailed specs and was very professional. Fast shipping and perfect packaging.',
            createdAt: new Date('2024-04-08').toISOString(),
            updatedAt: new Date('2024-04-08').toISOString(),
        },
        {
            productId: 9,
            userId: 18,
            rating: 4,
            content: '佳能相机拍照效果很好，各项功能都正常。镜头很清晰，没有灰尘或划痕。卖家很专业，提供了使用说明和保养建议。包装保护得很好，运输没有问题。',
            createdAt: new Date('2024-04-10').toISOString(),
            updatedAt: new Date('2024-04-10').toISOString(),
        },
        {
            productId: 10,
            userId: 19,
            rating: 5,
            content: 'Dyson vacuum is incredible! Suction power is still very strong and all attachments work perfectly. Seller cleaned it thoroughly before shipping. Communication was excellent and delivery was super fast. Worth every penny!',
            createdAt: new Date('2024-04-12').toISOString(),
            updatedAt: new Date('2024-04-12').toISOString(),
        },
        {
            productId: 1,
            userId: 20,
            rating: 3,
            content: 'iPhone基本功能正常，但是充电口有点松动。屏幕状态还行，有几个小划痕。卖家沟通一般，回复不够及时。价格还算公道，但希望能更详细描述产品状态。',
            createdAt: new Date('2024-04-15').toISOString(),
            updatedAt: new Date('2024-04-15').toISOString(),
        },
        {
            productId: 11,
            userId: 2,
            rating: 5,
            content: 'Samsung TV picture quality is outstanding! No dead pixels and colors are vibrant. Remote works perfectly and all smart features function well. Seller was very helpful with delivery arrangement. Excellent value for a large screen TV.',
            createdAt: new Date('2024-04-18').toISOString(),
            updatedAt: new Date('2024-04-18').toISOString(),
        },
        {
            productId: 12,
            userId: 3,
            rating: 4,
            content: 'KitchenAid搅拌机工作很好，马力足够强劲。外观有一些使用痕迹但不影响功能。所有配件都齐全，卖家还提供了使用手册。发货及时，包装也很安全。',
            createdAt: new Date('2024-04-20').toISOString(),
            updatedAt: new Date('2024-04-20').toISOString(),
        },
        {
            productId: 13,
            userId: 4,
            rating: 4,
            content: 'Bike is in good condition, gears shift smoothly and brakes work well. Some minor rust spots but overall solid. Seller was honest about condition and provided maintenance tips. Good price for a quality bike. Happy with purchase.',
            createdAt: new Date('2024-04-22').toISOString(),
            updatedAt: new Date('2024-04-22').toISOString(),
        },
        {
            productId: 14,
            userId: 5,
            rating: 5,
            content: '书桌质量很好，木材结实，组装说明清楚。卖家包装得很仔细，没有任何损坏。尺寸完全符合描述，颜色也很漂亮。客服态度很好，回答问题很详细。非常满意！',
            createdAt: new Date('2024-04-25').toISOString(),
            updatedAt: new Date('2024-04-25').toISOString(),
        },
        {
            productId: 15,
            userId: 6,
            rating: 3,
            content: 'Designer bag looks authentic but has more wear than shown in photos. Strap shows significant use and interior has some stains. Seller communication was average. Price was fair considering condition but expected better based on listing.',
            createdAt: new Date('2024-04-28').toISOString(),
            updatedAt: new Date('2024-04-28').toISOString(),
        },
        {
            productId: 16,
            userId: 7,
            rating: 5,
            content: '电动工具套装很完整，所有工具都能正常工作。电池续航时间也不错，充电速度快。卖家很专业，提供了安全使用建议。包装保护得很好，工具箱也很实用。',
            createdAt: new Date('2024-05-01').toISOString(),
            updatedAt: new Date('2024-05-01').toISOString(),
        },
        {
            productId: 17,
            userId: 8,
            rating: 4,
            content: 'Gaming chair is comfortable and all adjustments work smoothly. Fabric shows some wear but no tears or major damage. Assembly was straightforward with included tools. Seller provided good customer service and fast shipping.',
            createdAt: new Date('2024-05-03').toISOString(),
            updatedAt: new Date('2024-05-03').toISOString(),
        },
        {
            productId: 18,
            userId: 9,
            rating: 5,
            content: '空气净化器效果很好，运行声音也很安静。过滤网状态不错，卖家还提供了更换建议。外观几乎像新的，功能全部正常。性价比很高，推荐购买！',
            createdAt: new Date('2024-05-05').toISOString(),
            updatedAt: new Date('2024-05-05').toISOString(),
        },
        {
            productId: 19,
            userId: 10,
            rating: 2,
            content: 'Fitness equipment has several issues not mentioned in listing. Resistance mechanism is not working properly and display is flickering. Seller was unresponsive to messages after purchase. Would not recommend this seller.',
            createdAt: new Date('2024-05-08').toISOString(),
            updatedAt: new Date('2024-05-08').toISOString(),
        },
        {
            productId: 20,
            userId: 11,
            rating: 4,
            content: '咖啡机制作的咖啡味道很好，温度控制准确。外观有轻微磨损但不影响使用。清洁很方便，操作简单。卖家服务态度好，发货也很及时。整体满意这次购买。',
            createdAt: new Date('2024-05-10').toISOString(),
            updatedAt: new Date('2024-05-10').toISOString(),
        },
        {
            productId: 2,
            userId: 12,
            rating: 5,
            content: 'Outstanding MacBook! Performance is excellent for video editing and coding. Battery life is still very good for a used laptop. Seller was extremely helpful and provided original accessories. Fast shipping and perfect condition as described.',
            createdAt: new Date('2024-05-12').toISOString(),
            updatedAt: new Date('2024-05-12').toISOString(),
        },
        {
            productId: 3,
            userId: 13,
            rating: 4,
            content: 'iPad Pro很适合绘画和工作，屏幕显示效果很好。Apple Pencil响应很灵敏，没有延迟。有几个小划痕但不影响使用。卖家态度很好，回答问题很耐心。',
            createdAt: new Date('2024-05-15').toISOString(),
            updatedAt: new Date('2024-05-15').toISOString(),
        },
        {
            productId: 4,
            userId: 14,
            rating: 3,
            content: 'AirPods connection can be unstable sometimes and left earbud volume is slightly lower. Case has scratches not shown in photos. Seller communication was okay but shipping took longer than expected. Average experience overall.',
            createdAt: new Date('2024-05-18').toISOString(),
            updatedAt: new Date('2024-05-18').toISOString(),
        },
        {
            productId: 5,
            userId: 15,
            rating: 5,
            content: 'Nintendo Switch完美运行，所有游戏都没有问题。Joy-Con控制精准，屏幕清晰。卖家还包含了几个热门游戏。包装很仔细，客服回复及时。非常推荐！',
            createdAt: new Date('2024-05-20').toISOString(),
            updatedAt: new Date('2024-05-20').toISOString(),
        },
        {
            productId: 6,
            userId: 16,
            rating: 4,
            content: 'PS5 controller works well for most games, trigger feedback is good. Minor wear on analog sticks but functionality is not affected. Seller packed it well and shipping was fast. Good value for the price paid.',
            createdAt: new Date('2024-05-22').toISOString(),
            updatedAt: new Date('2024-05-22').toISOString(),
        },
        {
            productId: 7,
            userId: 17,
            rating: 4,
            content: 'Apple Watch健康监测功能都正常，GPS定位准确。表带有些磨损但可以更换。续航时间还可以接受，一天一充。卖家服务不错，解答了很多使用问题。',
            createdAt: new Date('2024-05-25').toISOString(),
            updatedAt: new Date('2024-05-25').toISOString(),
        },
        {
            productId: 8,
            userId: 18,
            rating: 5,
            content: 'Surface Pro exceeded expectations! Touch screen is responsive and pen input works flawlessly. Great for both work and entertainment. Seller included original charger and keyboard. Professional transaction and fast delivery.',
            createdAt: new Date('2024-05-28').toISOString(),
            updatedAt: new Date('2024-05-28').toISOString(),
        },
        {
            productId: 9,
            userId: 19,
            rating: 3,
            content: '佳能相机拍照质量还行，但是自动对焦有时候会比较慢。镜头清晰度不错，色彩还原也可以。卖家态度一般，回复不够积极。价格合理但期望更好的服务。',
            createdAt: new Date('2024-05-30').toISOString(),
            updatedAt: new Date('2024-05-30').toISOString(),
        },
        {
            productId: 10,
            userId: 20,
            rating: 5,
            content: 'Amazing Dyson vacuum cleaner! Suction is incredibly powerful and works on all surfaces. All attachments included and in great condition. Seller was professional and shipped quickly. Best purchase for home cleaning!',
            createdAt: new Date('2024-06-01').toISOString(),
            updatedAt: new Date('2024-06-01').toISOString(),
        },
        {
            productId: 11,
            userId: 2,
            rating: 4,
            content: 'Samsung电视画质很棒，4K分辨率很清晰。智能系统运行流畅，应用响应快。遥控器功能齐全，设置简单。卖家帮助安排了专业配送，服务很周到。',
            createdAt: new Date('2024-06-03').toISOString(),
            updatedAt: new Date('2024-06-03').toISOString(),
        },
        {
            productId: 12,
            userId: 3,
            rating: 5,
            content: 'KitchenAid mixer is a powerhouse! Handles heavy dough easily and all speeds work perfectly. Comes with multiple attachments as described. Seller provided excellent customer service and careful packaging. Highly recommend!',
            createdAt: new Date('2024-06-05').toISOString(),
            updatedAt: new Date('2024-06-05').toISOString(),
        }
    ];

    await db.insert(productReviews).values(sampleReviews);
    
    console.log('✅ Product reviews seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});