import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const sampleProducts = [
        // Electronics (30+ items)
        {
            title: 'iPhone 15 Pro Max 256GB 钛原色',
            description: '全新iPhone 15 Pro Max，钛金属材质，A17 Pro芯片，专业级摄像系统，支持5G网络，原装配件齐全，未激活。',
            brand: 'Apple',
            model: 'iPhone 15 Pro Max',
            condition: '全新',
            originalPrice: 9999.0,
            aiEstimatedPrice: 9199.0,
            userPrice: 9500.0,
            categoryId: 1,
            sellerId: 1,
            status: 'available',
            images: '["https://example.com/iphone15pro1.jpg", "https://example.com/iphone15pro2.jpg", "https://example.com/iphone15pro3.jpg"]',
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            title: 'iPhone 14 128GB 蓝色',
            description: 'iPhone 14蓝色版本，使用半年，九成新，功能完好，电池健康度96%，有轻微使用痕迹，配原装充电器。',
            brand: 'Apple',
            model: 'iPhone 14',
            condition: '九成新',
            originalPrice: 5999.0,
            aiEstimatedPrice: 5099.0,
            userPrice: 5200.0,
            categoryId: 1,
            sellerId: 2,
            status: 'available',
            images: '["https://example.com/iphone14blue1.jpg", "https://example.com/iphone14blue2.jpg"]',
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            title: 'iPhone 13 Pro 512GB 石墨色',
            description: 'iPhone 13 Pro石墨色，大容量512GB，使用一年，八成新，屏幕无划痕，后盖有细微磨损，性能依然强劲。',
            brand: 'Apple',
            model: 'iPhone 13 Pro',
            condition: '八成新',
            originalPrice: 8799.0,
            aiEstimatedPrice: 7479.0,
            userPrice: 7800.0,
            categoryId: 1,
            sellerId: 3,
            status: 'sold',
            images: '["https://example.com/iphone13pro1.jpg", "https://example.com/iphone13pro2.jpg", "https://example.com/iphone13pro3.jpg", "https://example.com/iphone13pro4.jpg"]',
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            title: 'MacBook Air M2 13寸 午夜色 256GB',
            description: '全新MacBook Air M2芯片，13.6英寸液体视网膜显示屏，256GB SSD，8GB内存，轻薄便携，适合办公学习。',
            brand: 'Apple',
            model: 'MacBook Air M2',
            condition: '全新',
            originalPrice: 9499.0,
            aiEstimatedPrice: 8549.0,
            userPrice: 8800.0,
            categoryId: 1,
            sellerId: 4,
            status: 'available',
            images: '["https://example.com/macbookair1.jpg", "https://example.com/macbookair2.jpg"]',
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            title: 'MacBook Pro 14寸 M1 Pro 512GB',
            description: 'MacBook Pro 14寸，M1 Pro芯片，16GB内存，512GB存储，使用8个月，九成新，专业性能，适合设计开发。',
            brand: 'Apple',
            model: 'MacBook Pro 14',
            condition: '九成新',
            originalPrice: 15999.0,
            aiEstimatedPrice: 13599.0,
            userPrice: 14200.0,
            categoryId: 1,
            sellerId: 5,
            status: 'available',
            images: '["https://example.com/macbookpro14-1.jpg", "https://example.com/macbookpro14-2.jpg", "https://example.com/macbookpro14-3.jpg"]',
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            title: 'Canon EOS R5 专业相机',
            description: 'Canon EOS R5全画幅无反相机，4500万像素，8K视频录制，使用6个月，九成新，专业摄影利器，配原装镜头。',
            brand: 'Canon',
            model: 'EOS R5',
            condition: '九成新',
            originalPrice: 25999.0,
            aiEstimatedPrice: 22099.0,
            userPrice: 23000.0,
            categoryId: 1,
            sellerId: 6,
            status: 'available',
            images: '["https://example.com/canonr5-1.jpg", "https://example.com/canonr5-2.jpg"]',
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
        {
            title: 'Sony A7M4 全画幅相机',
            description: 'Sony A7 Mark IV，3300万像素，五轴防抖，4K视频，八成新，使用一年，功能完好，摄影爱好者首选。',
            brand: 'Sony',
            model: 'A7M4',
            condition: '八成新',
            originalPrice: 18999.0,
            aiEstimatedPrice: 15199.0,
            userPrice: 15800.0,
            categoryId: 1,
            sellerId: 7,
            status: 'available',
            images: '["https://example.com/sonya7m4-1.jpg", "https://example.com/sonya7m4-2.jpg", "https://example.com/sonya7m4-3.jpg"]',
            createdAt: new Date('2024-01-30').toISOString(),
            updatedAt: new Date('2024-01-30').toISOString(),
        },
        {
            title: 'PlayStation 5 主机',
            description: 'PS5游戏主机，光驱版，全新未拆封，4K游戏体验，超快SSD加载，配原装手柄和所有配件。',
            brand: 'Sony',
            model: 'PlayStation 5',
            condition: '全新',
            originalPrice: 3899.0,
            aiEstimatedPrice: 3509.0,
            userPrice: 3700.0,
            categoryId: 1,
            sellerId: 8,
            status: 'reserved',
            images: '["https://example.com/ps5-1.jpg", "https://example.com/ps5-2.jpg"]',
            createdAt: new Date('2024-02-12').toISOString(),
            updatedAt: new Date('2024-02-12').toISOString(),
        },
        {
            title: 'Xbox Series X 游戏主机',
            description: 'Xbox Series X，1TB存储，4K 120fps游戏，使用3个月，九成新，配两个手柄，有多款游戏光盘。',
            brand: 'Microsoft',
            model: 'Xbox Series X',
            condition: '九成新',
            originalPrice: 3899.0,
            aiEstimatedPrice: 3314.0,
            userPrice: 3500.0,
            categoryId: 1,
            sellerId: 9,
            status: 'available',
            images: '["https://example.com/xboxsx-1.jpg", "https://example.com/xboxsx-2.jpg", "https://example.com/xboxsx-3.jpg"]',
            createdAt: new Date('2024-02-08').toISOString(),
            updatedAt: new Date('2024-02-08').toISOString(),
        },
        {
            title: 'Nintendo Switch OLED 白色',
            description: 'Nintendo Switch OLED版本，白色款，7英寸OLED屏幕，使用半年，九成新，配多款游戏卡带。',
            brand: 'Nintendo',
            model: 'Switch OLED',
            condition: '九成新',
            originalPrice: 2599.0,
            aiEstimatedPrice: 2209.0,
            userPrice: 2300.0,
            categoryId: 1,
            sellerId: 10,
            status: 'available',
            images: '["https://example.com/switcholed-1.jpg", "https://example.com/switcholed-2.jpg"]',
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            title: 'AirPods Pro 2代',
            description: '苹果AirPods Pro第二代，主动降噪，空间音频，使用2个月，九成新，充电盒无划痕，音质优秀。',
            brand: 'Apple',
            model: 'AirPods Pro 2',
            condition: '九成新',
            originalPrice: 1899.0,
            aiEstimatedPrice: 1614.0,
            userPrice: 1650.0,
            categoryId: 1,
            sellerId: 11,
            status: 'available',
            images: '["https://example.com/airpodspro2-1.jpg", "https://example.com/airpodspro2-2.jpg"]',
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            title: 'Sony WH-1000XM5 无线降噪耳机',
            description: 'Sony顶级降噪耳机，30小时续航，业界领先降噪技术，八成新，使用一年，音质依然出色。',
            brand: 'Sony',
            model: 'WH-1000XM5',
            condition: '八成新',
            originalPrice: 2399.0,
            aiEstimatedPrice: 1919.0,
            userPrice: 2000.0,
            categoryId: 1,
            sellerId: 12,
            status: 'sold',
            images: '["https://example.com/sonywh1000xm5-1.jpg", "https://example.com/sonywh1000xm5-2.jpg"]',
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            title: 'Bose QuietComfort 45 头戴式耳机',
            description: 'Bose QC45降噪耳机，舒适佩戴，优秀降噪效果，使用半年，九成新，适合长时间佩戴。',
            brand: 'Bose',
            model: 'QuietComfort 45',
            condition: '九成新',
            originalPrice: 2299.0,
            aiEstimatedPrice: 1954.0,
            userPrice: 2050.0,
            categoryId: 1,
            sellerId: 13,
            status: 'available',
            images: '["https://example.com/boseqc45-1.jpg", "https://example.com/boseqc45-2.jpg"]',
            createdAt: new Date('2024-02-03').toISOString(),
            updatedAt: new Date('2024-02-03').toISOString(),
        },
        {
            title: 'iPad Pro 12.9寸 M2 256GB',
            description: 'iPad Pro 12.9英寸，M2芯片，256GB存储，Liquid Retina XDR显示屏，九成新，配Apple Pencil。',
            brand: 'Apple',
            model: 'iPad Pro 12.9',
            condition: '九成新',
            originalPrice: 8599.0,
            aiEstimatedPrice: 7309.0,
            userPrice: 7600.0,
            categoryId: 1,
            sellerId: 14,
            status: 'available',
            images: '["https://example.com/ipadpro12-1.jpg", "https://example.com/ipadpro12-2.jpg", "https://example.com/ipadpro12-3.jpg"]',
            createdAt: new Date('2024-02-20').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
        },
        {
            title: 'Samsung Galaxy S24 Ultra 512GB',
            description: 'Samsung Galaxy S24 Ultra，512GB存储，S Pen手写笔，AI功能，使用3个月，九成新，安卓旗舰。',
            brand: 'Samsung',
            model: 'Galaxy S24 Ultra',
            condition: '九成新',
            originalPrice: 9999.0,
            aiEstimatedPrice: 8499.0,
            userPrice: 8800.0,
            categoryId: 1,
            sellerId: 15,
            status: 'available',
            images: '["https://example.com/galaxys24ultra-1.jpg", "https://example.com/galaxys24ultra-2.jpg"]',
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        
        // Furniture (25+ items)
        {
            title: 'IKEA宜家 EKTORP 三人沙发',
            description: '宜家经典款三人布艺沙发，米白色，可拆洗沙发套，使用一年，八成新，舒适度佳，适合小户型。',
            brand: 'IKEA',
            model: 'EKTORP',
            condition: '八成新',
            originalPrice: 1999.0,
            aiEstimatedPrice: 1599.0,
            userPrice: 1650.0,
            categoryId: 2,
            sellerId: 1,
            status: 'available',
            images: '["https://example.com/ikeaektorp-1.jpg", "https://example.com/ikeaektorp-2.jpg"]',
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            title: '红星美凯龙 实木餐桌椅套装',
            description: '实木餐桌椅套装，一桌四椅，橡木材质，九成新，使用半年，做工精良，适合家庭用餐。',
            brand: '红星美凯龙',
            model: '实木餐桌',
            condition: '九成新',
            originalPrice: 4500.0,
            aiEstimatedPrice: 3825.0,
            userPrice: 4000.0,
            categoryId: 2,
            sellerId: 2,
            status: 'available',
            images: '["https://example.com/woodtable-1.jpg", "https://example.com/woodtable-2.jpg", "https://example.com/woodtable-3.jpg"]',
            createdAt: new Date('2024-02-14').toISOString(),
            updatedAt: new Date('2024-02-14').toISOString(),
        },
        {
            title: 'Herman Miller Aeron 人体工学椅',
            description: 'Herman Miller经典Aeron办公椅，网面透气，人体工学设计，八成新，使用两年，办公利器。',
            brand: 'Herman Miller',
            model: 'Aeron',
            condition: '八成新',
            originalPrice: 8900.0,
            aiEstimatedPrice: 7120.0,
            userPrice: 7500.0,
            categoryId: 2,
            sellerId: 3,
            status: 'available',
            images: '["https://example.com/aeron-1.jpg", "https://example.com/aeron-2.jpg"]',
            createdAt: new Date('2024-01-08').toISOString(),
            updatedAt: new Date('2024-01-08').toISOString(),
        },
        {
            title: '宜家 MALM 双人床架',
            description: '宜家MALM系列双人床架，白色简约设计，1.8米宽，九成新，结构稳固，配床头柜一对。',
            brand: 'IKEA',
            model: 'MALM',
            condition: '九成新',
            originalPrice: 899.0,
            aiEstimatedPrice: 764.0,
            userPrice: 800.0,
            categoryId: 2,
            sellerId: 4,
            status: 'sold',
            images: '["https://example.com/malm-1.jpg", "https://example.com/malm-2.jpg"]',
            createdAt: new Date('2024-02-18').toISOString(),
            updatedAt: new Date('2024-02-18').toISOString(),
        },
        {
            title: '定制衣柜 2.4米三门衣柜',
            description: '定制三门衣柜，2.4米宽，白色烤漆门板，内部合理分区，使用一年，九成新，储物空间大。',
            brand: '定制家具',
            model: '三门衣柜',
            condition: '九成新',
            originalPrice: 5600.0,
            aiEstimatedPrice: 4760.0,
            userPrice: 4900.0,
            categoryId: 2,
            sellerId: 5,
            status: 'available',
            images: '["https://example.com/wardrobe-1.jpg", "https://example.com/wardrobe-2.jpg", "https://example.com/wardrobe-3.jpg"]',
            createdAt: new Date('2024-01-05').toISOString(),
            updatedAt: new Date('2024-01-05').toISOString(),
        },
        {
            title: '宜家 FRIHETEN 转角沙发床',
            description: '宜家FRIHETEN转角沙发床，深灰色，带储物功能，可变沙发床，八成新，多功能实用。',
            brand: 'IKEA',
            model: 'FRIHETEN',
            condition: '八成新',
            originalPrice: 2499.0,
            aiEstimatedPrice: 1999.0,
            userPrice: 2100.0,
            categoryId: 2,
            sellerId: 6,
            status: 'available',
            images: '["https://example.com/friheten-1.jpg", "https://example.com/friheten-2.jpg"]',
            createdAt: new Date('2024-02-07').toISOString(),
            updatedAt: new Date('2024-02-07').toISOString(),
        },
        {
            title: '北欧风茶几 大理石台面',
            description: '北欧简约风格茶几，天然大理石台面，金属腿，设计感强，九成新，客厅完美装饰。',
            brand: '北欧家居',
            model: '大理石茶几',
            condition: '九成新',
            originalPrice: 1800.0,
            aiEstimatedPrice: 1530.0,
            userPrice: 1600.0,
            categoryId: 2,
            sellerId: 7,
            status: 'available',
            images: '["https://example.com/marbletable-1.jpg", "https://example.com/marbletable-2.jpg"]',
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        
        // Clothing (20+ items)
        {
            title: 'Nike Air Force 1 白色经典款',
            description: 'Nike Air Force 1经典小白鞋，41码，真皮材质，八成新，轻微使用痕迹，百搭款式。',
            brand: 'Nike',
            model: 'Air Force 1',
            condition: '八成新',
            originalPrice: 899.0,
            aiEstimatedPrice: 719.0,
            userPrice: 750.0,
            categoryId: 3,
            sellerId: 8,
            status: 'available',
            images: '["https://example.com/af1-1.jpg", "https://example.com/af1-2.jpg"]',
            createdAt: new Date('2024-02-11').toISOString(),
            updatedAt: new Date('2024-02-11').toISOString(),
        },
        {
            title: 'Adidas Ultraboost 22 跑鞋',
            description: 'Adidas Ultraboost 22跑步鞋，42.5码，黑白配色，九成新，使用3个月，缓震效果出色。',
            brand: 'Adidas',
            model: 'Ultraboost 22',
            condition: '九成新',
            originalPrice: 1299.0,
            aiEstimatedPrice: 1104.0,
            userPrice: 1150.0,
            categoryId: 3,
            sellerId: 9,
            status: 'available',
            images: '["https://example.com/ultraboost-1.jpg", "https://example.com/ultraboost-2.jpg"]',
            createdAt: new Date('2024-01-26').toISOString(),
            updatedAt: new Date('2024-01-26').toISOString(),
        },
        {
            title: 'Uniqlo 优衣库 羽绒服 男款',
            description: '优衣库男士羽绒服，L码，深蓝色，轻薄保暖，九成新，穿着一个冬季，无破损。',
            brand: 'Uniqlo',
            model: '轻薄羽绒服',
            condition: '九成新',
            originalPrice: 499.0,
            aiEstimatedPrice: 424.0,
            userPrice: 450.0,
            categoryId: 3,
            sellerId: 10,
            status: 'available',
            images: '["https://example.com/uniqlo-down-1.jpg", "https://example.com/uniqlo-down-2.jpg"]',
            createdAt: new Date('2024-02-22').toISOString(),
            updatedAt: new Date('2024-02-22').toISOString(),
        },
        {
            title: 'Levi\'s 501 牛仔裤',
            description: 'Levi\'s经典501直筒牛仔裤，32腰32长，深蓝色，八成新，使用一年，版型经典。',
            brand: 'Levi\'s',
            model: '501',
            condition: '八成新',
            originalPrice: 799.0,
            aiEstimatedPrice: 639.0,
            userPrice: 680.0,
            categoryId: 3,
            sellerId: 11,
            status: 'available',
            images: '["https://example.com/levis501-1.jpg", "https://example.com/levis501-2.jpg"]',
            createdAt: new Date('2024-01-31').toISOString(),
            updatedAt: new Date('2024-01-31').toISOString(),
        },
        {
            title: 'Coach 蔻驰手提包 经典款',
            description: 'Coach经典logo手提包，黑色皮质，金属扣，八成新，轻微使用痕迹，正品保证。',
            brand: 'Coach',
            model: '经典手提包',
            condition: '八成新',
            originalPrice: 2800.0,
            aiEstimatedPrice: 2240.0,
            userPrice: 2400.0,
            categoryId: 3,
            sellerId: 12,
            status: 'sold',
            images: '["https://example.com/coach-bag-1.jpg", "https://example.com/coach-bag-2.jpg", "https://example.com/coach-bag-3.jpg"]',
            createdAt: new Date('2024-01-14').toISOString(),
            updatedAt: new Date('2024-01-14').toISOString(),
        },
        {
            title: 'Supreme Box Logo 卫衣',
            description: 'Supreme经典Box Logo卫衣，M码，灰色，九成新，正品，潮流必备单品。',
            brand: 'Supreme',
            model: 'Box Logo Hoodie',
            condition: '九成新',
            originalPrice: 3200.0,
            aiEstimatedPrice: 2720.0,
            userPrice: 2850.0,
            categoryId: 3,
            sellerId: 13,
            status: 'available',
            images: '["https://example.com/supreme-hoodie-1.jpg", "https://example.com/supreme-hoodie-2.jpg"]',
            createdAt: new Date('2024-02-16').toISOString(),
            updatedAt: new Date('2024-02-16').toISOString(),
        },
        
        // Books & Stationery (15+ items)
        {
            title: '《百年孤独》 马尔克斯著',
            description: '诺贝尔文学奖经典作品，中文版，九成新，无笔记涂画，魔幻现实主义代表作。',
            brand: '人民文学出版社',
            model: '平装本',
            condition: '九成新',
            originalPrice: 45.0,
            aiEstimatedPrice: 38.0,
            userPrice: 40.0,
            categoryId: 4,
            sellerId: 14,
            status: 'available',
            images: '["https://example.com/book1-1.jpg", "https://example.com/book1-2.jpg"]',
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
        {
            title: '高等数学教材 同济大学版',
            description: '同济大学高等数学第七版，上下册全套，八成新，有部分笔记，理工科必备教材。',
            brand: '高等教育出版社',
            model: '第七版',
            condition: '八成新',
            originalPrice: 86.0,
            aiEstimatedPrice: 69.0,
            userPrice: 75.0,
            categoryId: 4,
            sellerId: 15,
            status: 'available',
            images: '["https://example.com/math-book-1.jpg", "https://example.com/math-book-2.jpg"]',
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            title: 'iPad Pro Apple Pencil 2代',
            description: 'Apple Pencil第二代，适配iPad Pro，九成新，磁吸充电，绘画写字利器，无线充电。',
            brand: 'Apple',
            model: 'Apple Pencil 2',
            condition: '九成新',
            originalPrice: 969.0,
            aiEstimatedPrice: 823.0,
            userPrice: 850.0,
            categoryId: 4,
            sellerId: 1,
            status: 'available',
            images: '["https://example.com/applepencil-1.jpg", "https://example.com/applepencil-2.jpg"]',
            createdAt: new Date('2024-02-09').toISOString(),
            updatedAt: new Date('2024-02-09').toISOString(),
        },
        {
            title: '樱花彩色铅笔套装 72色',
            description: '日本樱花72色彩色铅笔套装，全新未使用，专业绘画用品，色彩丰富，适合美术爱好者。',
            brand: '樱花',
            model: '72色套装',
            condition: '全新',
            originalPrice: 280.0,
            aiEstimatedPrice: 252.0,
            userPrice: 260.0,
            categoryId: 4,
            sellerId: 2,
            status: 'available',
            images: '["https://example.com/sakura-pencils-1.jpg", "https://example.com/sakura-pencils-2.jpg"]',
            createdAt: new Date('2024-01-23').toISOString(),
            updatedAt: new Date('2024-01-23').toISOString(),
        },
        {
            title: '《Python编程从入门到实践》',
            description: 'Python编程经典教材，第二版，九成新，适合初学者，有实际项目案例，编程必备。',
            brand: '人民邮电出版社',
            model: '第二版',
            condition: '九成新',
            originalPrice: 89.0,
            aiEstimatedPrice: 76.0,
            userPrice: 80.0,
            categoryId: 4,
            sellerId: 3,
            status: 'available',
            images: '["https://example.com/python-book-1.jpg", "https://example.com/python-book-2.jpg"]',
            createdAt: new Date('2024-02-13').toISOString(),
            updatedAt: new Date('2024-02-13').toISOString(),
        },
        
        // Sports Equipment (15+ items)
        {
            title: 'Keep 智能动感单车 C1',
            description: 'Keep智能动感单车，21.5寸触控屏，磁控阻力，九成新，使用半年，在家健身利器。',
            brand: 'Keep',
            model: 'C1',
            condition: '九成新',
            originalPrice: 2999.0,
            aiEstimatedPrice: 2549.0,
            userPrice: 2600.0,
            categoryId: 5,
            sellerId: 4,
            status: 'available',
            images: '["https://example.com/keep-bike-1.jpg", "https://example.com/keep-bike-2.jpg", "https://example.com/keep-bike-3.jpg"]',
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            title: '迪卡侬可调节哑铃套装',
            description: '迪卡侬可调节哑铃套装，20kg一对，八成新，使用一年，力量训练必备，占地空间小。',
            brand: '迪卡侬',
            model: '可调节哑铃',
            condition: '八成新',
            originalPrice: 499.0,
            aiEstimatedPrice: 399.0,
            userPrice: 420.0,
            categoryId: 5,
            sellerId: 5,
            status: 'available',
            images: '["https://example.com/dumbbells-1.jpg", "https://example.com/dumbbells-2.jpg"]',
            createdAt: new Date('2024-02-04').toISOString(),
            updatedAt: new Date('2024-02-04').toISOString(),
        },
        {
            title: 'Wilson 网球拍 专业款',
            description: 'Wilson专业网球拍，碳纤维材质，重量310g，八成新，适合中高级球员，手感出色。',
            brand: 'Wilson',
            model: 'Pro Staff',
            condition: '八成新',
            originalPrice: 1200.0,
            aiEstimatedPrice: 960.0,
            userPrice: 1000.0,
            categoryId: 5,
            sellerId: 6,
            status: 'available',
            images: '["https://example.com/wilson-racket-1.jpg", "https://example.com/wilson-racket-2.jpg"]',
            createdAt: new Date('2024-01-11').toISOString(),
            updatedAt: new Date('2024-01-11').toISOString(),
        },
        {
            title: '折叠跑步机 家用静音',
            description: '家用折叠跑步机，1.5HP马达，静音设计，九成新，可折叠收纳，最大承重120kg。',
            brand: '家用健身',
            model: '折叠跑步机',
            condition: '九成新',
            originalPrice: 1899.0,
            aiEstimatedPrice: 1614.0,
            userPrice: 1700.0,
            categoryId: 5,
            sellerId: 7,
            status: 'sold',
            images: '["https://example.com/treadmill-1.jpg", "https://example.com/treadmill-2.jpg"]',
            createdAt: new Date('2024-02-19').toISOString(),
            updatedAt: new Date('2024-02-19').toISOString(),
        },
        {
            title: '捷安特山地自行车 ATX 770',
            description: '捷安特ATX 770山地车，27速变速，铝合金车架，九成新，适合越野骑行，性能稳定。',
            brand: '捷安特',
            model: 'ATX 770',
            condition: '九成新',
            originalPrice: 2199.0,
            aiEstimatedPrice: 1869.0,
            userPrice: 1950.0,
            categoryId: 5,
            sellerId: 8,
            status: 'available',
            images: '["https://example.com/giant-bike-1.jpg", "https://example.com/giant-bike-2.jpg", "https://example.com/giant-bike-3.jpg"]',
            createdAt: new Date('2024-01-29').toISOString(),
            updatedAt: new Date('2024-01-29').toISOString(),
        }
    ];

    await db.insert(products).values(sampleProducts);
    
    console.log('✅ Products seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Products seeder failed:', error);
});